# This message contains ICRA buff debuff zone and lurk status data received from the referee system

std_msgs/Header header

bool f1_zone_status
uint8 f1_zone_buff_debuff_status

bool f2_zone_status
uint8 f2_zone_buff_debuff_status

bool f3_zone_status
uint8 f3_zone_buff_debuff_status

bool f4_zone_status
uint8 f4_zone_buff_debuff_status

bool f5_zone_status
uint8 f5_zone_buff_debuff_status

bool f6_zone_status
uint8 f6_zone_buff_debuff_status

uint16 red1_bullet_left
uint16 red2_bullet_left

uint16 blue1_bullet_left
uint16 blue2_bullet_left

uint8 lurk_mode
