# This message contains robot HP data received from the referee system

std_msgs/Header header

# red team
uint16 red_1_hero_hp
uint16 red_2_engineer_hp
uint16 red_3_infantry_hp
uint16 red_4_infantry_hp
uint16 red_5_infantry_hp
uint16 red_7_sentry_hp
uint16 red_outpost_hp
uint16 red_base_hp

# blue team
uint16 blue_1_hero_hp
uint16 blue_2_engineer_hp
uint16 blue_3_infantry_hp
uint16 blue_4_infantry_hp
uint16 blue_5_infantry_hp
uint16 blue_7_sentry_hp
uint16 blue_outpost_hp
uint16 blue_base_hp
